/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Grindi (https://sketchfab.com/ranok777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/finance-bank-f0e5898e743c460ba01fb1e8b58b72d0
Title: Finance bank
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BankModel(props) {
    const { nodes, materials } = useGLTF('/bank.glb')
    return (
        <group {...props} dispose={null}>
            <group position={[0, 0.842, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.913}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_23.geometry}
                    material={materials['coin.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_24.geometry}
                    material={materials['coin_x.002']}
                />
            </group>
            <group position={[0.75, 0, 0.75]} scale={[0.698, 1, 0.698]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.stone}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials.stone_d}
                />
            </group>
            <group position={[0.75, 0, -0.75]} scale={[0.698, 1, 0.698]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials.stone}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials.stone_d}
                />
            </group>
            <group position={[-0.75, 0, 0.75]} scale={[0.698, 1, 0.698]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_11.geometry}
                    material={materials.stone}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_12.geometry}
                    material={materials.stone_d}
                />
            </group>
            <group position={[-0.75, 0, -0.75]} scale={[0.698, 1, 0.698]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials.stone}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_15.geometry}
                    material={materials.stone_d}
                />
            </group>
            <group scale={[1.414, 0.843, 1.414]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials.stone}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_18.geometry}
                    material={materials.stone_d}
                />
            </group>
            <group position={[0, 1.428, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_20.geometry}
                    material={materials.stone}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_21.geometry}
                    material={materials.stone_d}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/bank.glb')