/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Glowbox 3D (https://sketchfab.com/ra3id)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foosball-table-f2509fdfa22341cc82d8b95c188efbc0
Title: Foosball Table
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function ITSFModel(props) {
    const { nodes, materials } = useGLTF('/itsf.glb')
    return (
        <group {...props} dispose={null}>
            <group position={[0.232, 184.571, -0.225]} rotation={[-Math.PI / 2, 0, 0]} scale={4.935}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Ball_NEw002_Material_0.geometry}
                    material={materials.Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Ball_NEw002_Material_0_1.geometry}
                    material={materials.Material}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/itsf.glb')