/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mateusz Woliński (https://sketchfab.com/jeandiz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/swat-operator-9e82fabf26194896b5ad4a364d864eab
Title: SWAT operator
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF } from '@react-three/drei'

export function PoliceModel(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/police.glb')

    useEffect(() => {

    }, []);
    // const { actions } = useAnimations(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="root">
                        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                            <group name="Armature_100" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                                <group name="GLTF_created_0">
                                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                                    <skinnedMesh
                                        name="Object_7"
                                        geometry={nodes.Object_7.geometry}
                                        material={materials.boots}
                                        skeleton={nodes.Object_7.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_9"
                                        geometry={nodes.Object_9.geometry}
                                        material={materials.boots}
                                        skeleton={nodes.Object_9.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_11"
                                        geometry={nodes.Object_11.geometry}
                                        material={materials.helmet}
                                        skeleton={nodes.Object_11.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_13"
                                        geometry={nodes.Object_13.geometry}
                                        material={materials.face}
                                        skeleton={nodes.Object_13.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_15"
                                        geometry={nodes.Object_15.geometry}
                                        material={materials.eyes}
                                        skeleton={nodes.Object_15.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_17"
                                        geometry={nodes.Object_17.geometry}
                                        material={materials['lambert1.003']}
                                        skeleton={nodes.Object_17.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_19"
                                        geometry={nodes.Object_19.geometry}
                                        material={materials['lambert1.003']}
                                        skeleton={nodes.Object_19.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_21"
                                        geometry={nodes.Object_21.geometry}
                                        material={materials['lambert1.003']}
                                        skeleton={nodes.Object_21.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_23"
                                        geometry={nodes.Object_23.geometry}
                                        material={materials['lambert1.003']}
                                        skeleton={nodes.Object_23.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_25"
                                        geometry={nodes.Object_25.geometry}
                                        material={materials.mask}
                                        skeleton={nodes.Object_25.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_27"
                                        geometry={nodes.Object_27.geometry}
                                        material={materials.night_vis_goggles}
                                        skeleton={nodes.Object_27.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_29"
                                        geometry={nodes.Object_29.geometry}
                                        material={materials.pouch}
                                        skeleton={nodes.Object_29.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_31"
                                        geometry={nodes.Object_31.geometry}
                                        material={materials.pouch}
                                        skeleton={nodes.Object_31.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_33"
                                        geometry={nodes.Object_33.geometry}
                                        material={materials.pouch}
                                        skeleton={nodes.Object_33.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_35"
                                        geometry={nodes.Object_35.geometry}
                                        material={materials.pouch}
                                        skeleton={nodes.Object_35.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_37"
                                        geometry={nodes.Object_37.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_37.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_39"
                                        geometry={nodes.Object_39.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_39.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_41"
                                        geometry={nodes.Object_41.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_41.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_43"
                                        geometry={nodes.Object_43.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_43.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_45"
                                        geometry={nodes.Object_45.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_45.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_47"
                                        geometry={nodes.Object_47.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_47.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_49"
                                        geometry={nodes.Object_49.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_49.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_51"
                                        geometry={nodes.Object_51.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_51.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_53"
                                        geometry={nodes.Object_53.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_53.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_55"
                                        geometry={nodes.Object_55.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_55.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_57"
                                        geometry={nodes.Object_57.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_57.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_59"
                                        geometry={nodes.Object_59.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_59.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_61"
                                        geometry={nodes.Object_61.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_61.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_63"
                                        geometry={nodes.Object_63.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_63.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_65"
                                        geometry={nodes.Object_65.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_65.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_67"
                                        geometry={nodes.Object_67.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_67.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_69"
                                        geometry={nodes.Object_69.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_69.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_71"
                                        geometry={nodes.Object_71.geometry}
                                        material={materials.gloves}
                                        skeleton={nodes.Object_71.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_73"
                                        geometry={nodes.Object_73.geometry}
                                        material={materials.gloves}
                                        skeleton={nodes.Object_73.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_75"
                                        geometry={nodes.Object_75.geometry}
                                        material={materials.uniform}
                                        skeleton={nodes.Object_75.skeleton}
                                    />
                                    <group name="boot_lp_65" />
                                    <group name="boot_lp001_66" />
                                    <group name="helmet_Mesh008_67" />
                                    <group name="humanBody001_humanBodyMesh002_68" />
                                    <group name="humanHighPolyEyes_humanHighPolyEyesMesh001_69" />
                                    <group name="magazine001_Mesh001_70" />
                                    <group name="magazine002_Mesh003_71" />
                                    <group name="magazine003_Mesh004_72" />
                                    <group name="magazine_Mesh002_73" />
                                    <group name="mask_meshId0_name_74" />
                                    <group name="night_vision_goggles_Mesh010_75" />
                                    <group name="pouch001_meshId0_name001_76" />
                                    <group name="pouch002_meshId0_name003_77" />
                                    <group name="pouch003_meshId0_name004_78" />
                                    <group name="pouch_meshId0_name005_79" />
                                    <group name="sol_10_low_80" />
                                    <group name="sol_11_low_81" />
                                    <group name="sol_13_low_82" />
                                    <group name="sol_20_low_83" />
                                    <group name="sol_21_low_84" />
                                    <group name="sol_22_low_85" />
                                    <group name="sol_23_low_86" />
                                    <group name="sol_24_low_87" />
                                    <group name="sol_24_low001_88" />
                                    <group name="sol_24_low002_89" />
                                    <group name="sol_25_low_90" />
                                    <group name="sol_29_low_91" />
                                    <group name="sol_30_low_92" />
                                    <group name="sol_39_low_93" />
                                    <group name="sol_4_low_94" />
                                    <group name="sol_5_low_95" />
                                    <group name="sol_6_low_96" />
                                    <group name="sol_7_low001_sol_7_low003_97" />
                                    <group name="sol_7_low002_98" />
                                    <group name="sol_8_low_sol_8_low001_99" />
                                </group>
                            </group>
                            <group
                                name="part_2_low_101"
                                position={[-0.014, 1.073, 0.22]}
                                rotation={[-2.367, -1.28, -2.442]}
                                scale={1.134}>
                                <mesh
                                    name="Object_142"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_142.geometry}
                                    material={materials['lambert1.003']}
                                />
                                <mesh
                                    name="Object_143"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_143.geometry}
                                    material={materials.material}
                                />
                                <mesh
                                    name="Object_144"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_144.geometry}
                                    material={materials.material_11}
                                />
                                <mesh
                                    name="Object_145"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_145.geometry}
                                    material={materials.material_12}
                                />
                                <mesh
                                    name="Object_146"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_146.geometry}
                                    material={materials.material_13}
                                />
                            </group>
                            <group
                                name="Circle_102"
                                position={[-0.295, 1.426, 0.006]}
                                rotation={[-1.508, -0.867, -1.717]}
                                scale={0.011}>
                                <mesh
                                    name="Object_148"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_148.geometry}
                                    material={materials.patch}
                                />
                            </group>
                            <group name="Plane_103" position={[0.036, 1.498, -0.165]}>
                                <mesh
                                    name="Object_150"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_150.geometry}
                                    material={materials.patch}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/police.glb')